// <auto-generated />
using System;
using ArarasHealthHub.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ArarasHealthHub.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260605195626_a2h_1.0.2")]
    partial class a2h_102
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ArarasHealthHub.Domain.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Identificador único do registro.");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)")
                        .HasComment("CPF");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2")
                        .HasComment("Data de criação do registro.");

                    b.Property<string>("Function")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Função");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasComment("Indica se o registro está ativo.");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Nome do funcionário");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasComment("Telefone");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2")
                        .HasComment("Data da última atualização do registro.");

                    b.HasKey("Id");

                    b.HasIndex("Cpf")
                        .IsUnique();

                    b.ToTable("Employees", null, t =>
                        {
                            t.HasComment("Representa um funcionário");
                        });
                });

            modelBuilder.Entity("ArarasHealthHub.Domain.Entities.Facility", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Identificador único do registro.");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cnes")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)")
                        .HasComment("Código CNES");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2")
                        .HasComment("Data de criação do registro.");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasComment("Indica se o registro está ativo.");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Nome da unidade");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2")
                        .HasComment("Data da última atualização do registro.");

                    b.HasKey("Id");

                    b.ToTable("Facilities", null, t =>
                        {
                            t.HasComment("Representa uma unidade");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cnes = "6345921",
                            CreatedOn = new DateTime(2025, 1, 2, 8, 35, 14, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Secretária Municipal da Saúde - Dr. João Geraldo Noronha"
                        });
                });

            modelBuilder.Entity("ArarasHealthHub.Domain.Entities.MainCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Identificador único do registro.");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2")
                        .HasComment("Data de criação do registro.");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasComment("Indica se o registro está ativo.");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Nome da categoria principal");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2")
                        .HasComment("Data da última atualização do registro.");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("MainCategories", null, t =>
                        {
                            t.HasComment("Representa uma categoria principal de produtos (ex: Medicamento, Material Hospitalar, Material de Limpeza)");
                        });
                });

            modelBuilder.Entity("ArarasHealthHub.Domain.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Identificador único do registro.");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ApprovedByAccountId")
                        .HasColumnType("int");

                    b.Property<int?>("ApprovedByEmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CanceledAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CanceledByAccountId")
                        .HasColumnType("int");

                    b.Property<int?>("CanceledByEmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedByAccountId")
                        .HasColumnType("int");

                    b.Property<int>("CreatedByEmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2")
                        .HasComment("Data de criação do registro.");

                    b.Property<DateTime?>("FinalizedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FinalizedByAccountId")
                        .HasColumnType("int");

                    b.Property<int?>("FinalizedByEmployeeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasComment("Indica se o registro está ativo.");

                    b.Property<string>("Observation")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("OrderFacilityId")
                        .HasColumnType("int");

                    b.Property<int>("OrderStatusId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SeparatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("SeparatedByAccountId")
                        .HasColumnType("int");

                    b.Property<int?>("SeparatedByEmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2")
                        .HasComment("Data da última atualização do registro.");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedByAccountId");

                    b.HasIndex("ApprovedByEmployeeId");

                    b.HasIndex("CanceledByAccountId");

                    b.HasIndex("CanceledByEmployeeId");

                    b.HasIndex("CreatedByAccountId");

                    b.HasIndex("CreatedByEmployeeId");

                    b.HasIndex("FinalizedByAccountId");

                    b.HasIndex("FinalizedByEmployeeId");

                    b.HasIndex("OrderFacilityId");

                    b.HasIndex("OrderStatusId");

                    b.HasIndex("SeparatedByAccountId");

                    b.HasIndex("SeparatedByEmployeeId");

                    b.ToTable("Orders", null, t =>
                        {
                            t.HasComment("Representa um pedido de dispensação");
                        });
                });

            modelBuilder.Entity("ArarasHealthHub.Domain.Entities.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Identificador único do registro.");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("ActualQuantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal>("ApprovedQuantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2")
                        .HasComment("Data de criação do registro.");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasComment("Indica se o registro está ativo.");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<decimal>("RequestedQuantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal>("ReservedQuantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2")
                        .HasComment("Data da última atualização do registro.");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems", null, t =>
                        {
                            t.HasComment("Itens pertencentes ao pedido de dispensação");
                        });
                });

            modelBuilder.Entity("ArarasHealthHub.Domain.Entities.OrderItemLot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Identificador único do registro.");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2")
                        .HasComment("Data de criação do registro.");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasComment("Indica se o registro está ativo.");

                    b.Property<int>("OrderItemId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<int>("StockLotId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2")
                        .HasComment("Data da última atualização do registro.");

                    b.HasKey("Id");

                    b.HasIndex("OrderItemId");

                    b.HasIndex("StockLotId");

                    b.ToTable("OrderItemLots", null, t =>
                        {
                            t.HasComment("Lotes efetivamente separados para atendimento do item do pedido");
                        });
                });

            modelBuilder.Entity("ArarasHealthHub.Domain.Entities.OrderReturn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Identificador único do registro.");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2")
                        .HasComment("Data de criação do registro.");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasComment("Indica se o registro está ativo.");

                    b.Property<int>("OriginalOrderId")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("ReturnedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ReturnedByAccountId")
                        .HasColumnType("int");

                    b.Property<int>("ReturnedByEmployeeId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalReturnedValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2")
                        .HasComment("Data da última atualização do registro.");

                    b.HasKey("Id");

                    b.HasIndex("OriginalOrderId");

                    b.HasIndex("ReturnedAt");

                    b.HasIndex("ReturnedByAccountId");

                    b.HasIndex("ReturnedByEmployeeId");

                    b.HasIndex("OriginalOrderId", "ReturnedAt");

                    b.ToTable("OrderReturns", null, t =>
                        {
                            t.HasComment("Representa devoluções de produtos dispensados em pedidos");
                        });
                });

            modelBuilder.Entity("ArarasHealthHub.Domain.Entities.OrderReturnItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Identificador único do registro.");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2")
                        .HasComment("Data de criação do registro.");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasComment("Indica se o registro está ativo.");

                    b.Property<int>("OrderReturnId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<int>("StockLotId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitValue")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2")
                        .HasComment("Data da última atualização do registro.");

                    b.HasKey("Id");

                    b.HasIndex("OrderReturnId");

                    b.HasIndex("ProductId");

                    b.HasIndex("StockLotId");

                    b.ToTable("OrderReturnItems", null, t =>
                        {
                            t.HasComment("Itens devolvidos ao estoque");

                            t.HasCheckConstraint("CK_OrderReturnItem_Quantity", "\"Quantity\" > 0");
                        });
                });

            modelBuilder.Entity("ArarasHealthHub.Domain.Entities.OrderStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Identificador único do registro.");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2")
                        .HasComment("Data de criação do registro.");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasComment("Indica se o registro está ativo.");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2")
                        .HasComment("Data da última atualização do registro.");

                    b.HasKey("Id");

                    b.HasIndex("Description")
                        .IsUnique();

                    b.ToTable("OrderStatuses", null, t =>
                        {
                            t.HasComment("Tabela de lookup dos status do pedido");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedOn = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Pendente de Aprovação",
                            IsActive = true
                        },
                        new
                        {
                            Id = 2,
                            CreatedOn = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Pronto para Separação",
                            IsActive = true
                        },
                        new
                        {
                            Id = 3,
                            CreatedOn = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Em Separação",
                            IsActive = true
                        },
                        new
                        {
                            Id = 4,
                            CreatedOn = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Pronto para Envio/Finalização",
                            IsActive = true
                        },
                        new
                        {
                            Id = 5,
                            CreatedOn = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Finalizado",
                            IsActive = true
                        },
                        new
                        {
                            Id = 6,
                            CreatedOn = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Cancelado",
                            IsActive = true
                        });
                });

            modelBuilder.Entity("ArarasHealthHub.Domain.Entities.PackagingType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Identificador único do registro.");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2")
                        .HasComment("Data de criação do registro.");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasComment("Indica se o registro está ativo.");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Nome do tipo de embalagem");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2")
                        .HasComment("Data da última atualização do registro.");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("PackagingTypes", null, t =>
                        {
                            t.HasComment("Representa um tipo de embalagem do produto (ex: Frasco, Ampola, Comprimido)");
                        });
                });

            modelBuilder.Entity("ArarasHealthHub.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Identificador único do registro.");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2")
                        .HasComment("Data de criação do registro.");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasComment("Descrição do produto");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasComment("Indica se o registro está ativo.");

                    b.Property<int>("MainCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasComment("Nome do produto");

                    b.Property<int>("PackagingTypeId")
                        .HasColumnType("int");

                    b.Property<int>("SubCategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2")
                        .HasComment("Data da última atualização do registro.");

                    b.HasKey("Id");

                    b.HasIndex("MainCategoryId");

                    b.HasIndex("PackagingTypeId");

                    b.HasIndex("SubCategoryId");

                    b.ToTable("Products", null, t =>
                        {
                            t.HasComment("Representa um produto");
                        });
                });

            modelBuilder.Entity("ArarasHealthHub.Domain.Entities.ReceivedItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Identificador único do registro.");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Batch")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2")
                        .HasComment("Data de criação do registro.");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasComment("Indica se o registro está ativo.");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<int>("ReceivingId")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2")
                        .HasComment("Data da última atualização do registro.");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("ReceivingId");

                    b.ToTable("ReceivedItems", null, t =>
                        {
                            t.HasComment("Representa um item específico de um recebimento");

                            t.HasCheckConstraint("CK_ReceivedItems_Quantity", "\"Quantity\" > 0");

                            t.HasCheckConstraint("CK_ReceivedItems_UnitValue", "\"UnitValue\" >= 0");
                        });
                });

            modelBuilder.Entity("ArarasHealthHub.Domain.Entities.Receiving", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Identificador único do registro.");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2")
                        .HasComment("Data de criação do registro.");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasComment("Indica se o registro está ativo.");

                    b.Property<string>("Observation")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("ReceivingDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ResponsibleId")
                        .HasColumnType("int");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int");

                    b.Property<string>("SupplyAuthorization")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2")
                        .HasComment("Data da última atualização do registro.");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("ResponsibleId");

                    b.HasIndex("SupplierId");

                    b.ToTable("Receivings", null, t =>
                        {
                            t.HasComment("Representa o registro de entrada de produtos no estoque");

                            t.HasCheckConstraint("CK_Receiving_InvoiceNumber", "[InvoiceNumber] <> ''");
                        });
                });

            modelBuilder.Entity("ArarasHealthHub.Domain.Entities.Stock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Identificador único do registro.");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2")
                        .HasComment("Data de criação do registro.");

                    b.Property<decimal>("CurrentQuantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasComment("Indica se o registro está ativo.");

                    b.Property<decimal>("MinQuantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<decimal>("ReservedQuantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2")
                        .HasComment("Data da última atualização do registro.");

                    b.HasKey("Id");

                    b.HasIndex("ProductId")
                        .IsUnique();

                    b.ToTable("Stocks", null, t =>
                        {
                            t.HasComment("Representa o estoque consolidado do produto");

                            t.HasCheckConstraint("CK_Stock_CurrentQuantity", "[CurrentQuantity] >= 0");

                            t.HasCheckConstraint("CK_Stock_ReservedQuantity", "[ReservedQuantity] >= 0");
                        });
                });

            modelBuilder.Entity("ArarasHealthHub.Domain.Entities.StockAdjustment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Identificador único do registro.");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<DateTime>("AdjustmentDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2")
                        .HasComment("Data de criação do registro.");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasComment("Indica se o registro está ativo.");

                    b.Property<string>("Observation")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("ResponsibleId")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2")
                        .HasComment("Data da última atualização do registro.");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("ResponsibleId");

                    b.ToTable("StockAdjustments", null, t =>
                        {
                            t.HasComment("Representa um ajuste manual de estoque");
                        });
                });

            modelBuilder.Entity("ArarasHealthHub.Domain.Entities.StockAdjustmentItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Identificador único do registro.");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Batch")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Brand")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2")
                        .HasComment("Data de criação do registro.");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasComment("Indica se o registro está ativo.");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<int>("StockAdjustmentId")
                        .HasColumnType("int");

                    b.Property<int?>("StockLotId")
                        .HasColumnType("int");

                    b.Property<decimal?>("TotalValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("UnitValue")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2")
                        .HasComment("Data da última atualização do registro.");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("StockAdjustmentId");

                    b.HasIndex("StockLotId");

                    b.ToTable("StockAdjustmentItems", null, t =>
                        {
                            t.HasComment("Itens de ajuste manual de estoque");

                            t.HasCheckConstraint("CK_StockAdjustmentItem_Quantity", "\"Quantity\" > 0");
                        });
                });

            modelBuilder.Entity("ArarasHealthHub.Domain.Entities.StockCost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Identificador único do registro.");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AverageUnitCost")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2")
                        .HasComment("Data de criação do registro.");

                    b.Property<decimal>("CurrentTotalCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasComment("Indica se o registro está ativo.");

                    b.Property<int>("StockId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2")
                        .HasComment("Data da última atualização do registro.");

                    b.HasKey("Id");

                    b.HasIndex("StockId")
                        .IsUnique();

                    b.ToTable("StockCosts", null, t =>
                        {
                            t.HasComment("Armazena o custo médio unitário do estoque");

                            t.HasCheckConstraint("CK_StockCost_AverageUnitCost", "[AverageUnitCost] >= 0");

                            t.HasCheckConstraint("CK_StockCost_CurrentTotalCost", "[CurrentTotalCost] >= 0");
                        });
                });

            modelBuilder.Entity("ArarasHealthHub.Domain.Entities.StockLot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Identificador único do registro.");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AvailableQuantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<string>("Batch")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2")
                        .HasComment("Data de criação do registro.");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasComment("Indica se o registro está ativo.");

                    b.Property<int?>("ReceivedItemId")
                        .HasColumnType("int");

                    b.Property<int>("StockId")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitValue")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2")
                        .HasComment("Data da última atualização do registro.");

                    b.HasKey("Id");

                    b.HasIndex("ReceivedItemId");

                    b.HasIndex("StockId", "Batch", "ExpiryDate");

                    b.ToTable("StockLots", null, t =>
                        {
                            t.HasComment("Representa o estoque por lote");

                            t.HasCheckConstraint("CK_StockLot_AvailableQuantity", "[AvailableQuantity] >= 0");

                            t.HasCheckConstraint("CK_StockLot_UnitValue", "[UnitValue] >= 0");
                        });
                });

            modelBuilder.Entity("ArarasHealthHub.Domain.Entities.StockMovement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Identificador único do registro.");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2")
                        .HasComment("Data de criação do registro.");

                    b.Property<int>("Direction")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasComment("Indica se o registro está ativo.");

                    b.Property<decimal>("MovementCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("MovementDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<int>("Reason")
                        .HasColumnType("int");

                    b.Property<int>("ResponsibleId")
                        .HasColumnType("int");

                    b.Property<int>("SourceDocumentId")
                        .HasColumnType("int");

                    b.Property<string>("SourceDocumentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("StockLotId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2")
                        .HasComment("Data da última atualização do registro.");

                    b.HasKey("Id");

                    b.HasIndex("Direction");

                    b.HasIndex("MovementDate");

                    b.HasIndex("Reason");

                    b.HasIndex("ResponsibleId");

                    b.HasIndex("StockLotId");

                    b.HasIndex("SourceDocumentId", "SourceDocumentType");

                    b.ToTable("StockMovements", null, t =>
                        {
                            t.HasComment("Histórico de movimentações de estoque");

                            t.HasCheckConstraint("CK_StockMovement_MovementCost", "[MovementCost] >= 0");

                            t.HasCheckConstraint("CK_StockMovement_Quantity", "[Quantity] > 0");
                        });
                });

            modelBuilder.Entity("ArarasHealthHub.Domain.Entities.SubCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Identificador único do registro.");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2")
                        .HasComment("Data de criação do registro.");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasComment("Indica se o registro está ativo.");

                    b.Property<int>("MainCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Nome da subcategoria");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2")
                        .HasComment("Data da última atualização do registro.");

                    b.HasKey("Id");

                    b.HasIndex("MainCategoryId", "Name")
                        .IsUnique();

                    b.ToTable("SubCategories", null, t =>
                        {
                            t.HasComment("Representa uma subcategoria vinculada a categoria principal de produtos (ex: Antibiótico, Analgésico, Antialérgico)");
                        });
                });

            modelBuilder.Entity("ArarasHealthHub.Domain.Entities.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Identificador único do registro.");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(18)
                        .HasColumnType("nvarchar(18)")
                        .HasComment("CNPJ");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2")
                        .HasComment("Data de criação do registro.");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasComment("Indica se o registro está ativo.");

                    b.Property<string>("LegalName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasComment("Razão Social");

                    b.Property<string>("TradeName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasComment("Nome Fantasia");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2")
                        .HasComment("Data da última atualização do registro.");

                    b.HasKey("Id");

                    b.ToTable("Suppliers", null, t =>
                        {
                            t.HasComment("Representa um fornecedor");
                        });
                });

            modelBuilder.Entity("ArarasHealthHub.Domain.Identity.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2")
                        .HasComment("Data de criação da conta.");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<int>("FacilityId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasComment("Indica se a conta está ativa.");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<byte>("Role")
                        .HasColumnType("tinyint")
                        .HasComment("Papel da conta no sistema.");

                    b.Property<byte>("Scope")
                        .HasColumnType("tinyint")
                        .HasComment("Escopo da conta no sistema.");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2")
                        .HasComment("Data da última atualização da conta.");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("FacilityId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("ApplicationUsers", null, t =>
                        {
                            t.HasComment("Representa uma conta de usuário do sistema");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "3F1C7B9A-1C8E-4E3B-A4F5-8C6B7F2E1D99",
                            CreatedOn = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "",
                            EmailConfirmed = false,
                            FacilityId = 1,
                            IsActive = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "",
                            NormalizedUserName = "SAUDE_MASTER",
                            PasswordHash = "AQAAAAIAAYagAAAAEEqeBGF+Rvx70SKaJEf8a7fAWWMLi+icLvnqu5uiLw3uR23FB+X6dxnr0jBGFs2ZnA==",
                            PhoneNumberConfirmed = false,
                            Role = (byte)1,
                            Scope = (byte)1,
                            SecurityStamp = "D8A2F6E1-7B32-4C6F-BB5A-91C3E62E8A11",
                            TwoFactorEnabled = false,
                            UserName = "saude_master"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ArarasHealthHub.Domain.Entities.Facility", b =>
                {
                    b.OwnsOne("ArarasHealthHub.Domain.ValueObjects.Address", "Address", b1 =>
                        {
                            b1.Property<int>("FacilityId")
                                .HasColumnType("int");

                            b1.Property<string>("Cep")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)")
                                .HasColumnName("Cep")
                                .HasComment("CEP");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("City")
                                .HasComment("Cidade");

                            b1.Property<string>("Complement")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Complement")
                                .HasComment("Complemento");

                            b1.Property<string>("Neighborhood")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Neighborhood")
                                .HasComment("Bairro");

                            b1.Property<string>("Number")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("Number")
                                .HasComment("Número");

                            b1.Property<string>("State")
                                .IsRequired()
                                .HasMaxLength(2)
                                .HasColumnType("nvarchar(2)")
                                .HasColumnName("State")
                                .HasComment("UF");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("Street")
                                .HasComment("Logradouro");

                            b1.HasKey("FacilityId");

                            b1.ToTable("Facilities", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("FacilityId");

                            b1.HasData(
                                new
                                {
                                    FacilityId = 1,
                                    Cep = "13601-111",
                                    City = "Araras",
                                    Complement = "",
                                    Neighborhood = "Jardim Belvedere",
                                    Number = "33",
                                    State = "SP",
                                    Street = "Rua Campos Sales"
                                });
                        });

                    b.OwnsOne("ArarasHealthHub.Domain.ValueObjects.Contact", "Contact", b1 =>
                        {
                            b1.Property<int>("FacilityId")
                                .HasColumnType("int");

                            b1.Property<string>("Email")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Email")
                                .HasComment("E-mail");

                            b1.Property<string>("Phone")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("Phone")
                                .HasComment("Telefone");

                            b1.HasKey("FacilityId");

                            b1.ToTable("Facilities", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("FacilityId");

                            b1.HasData(
                                new
                                {
                                    FacilityId = 1,
                                    Email = "saude@araras.sp.gov.br",
                                    Phone = "(19) 3543-1522"
                                });
                        });

                    b.Navigation("Address")
                        .IsRequired();

                    b.Navigation("Contact")
                        .IsRequired();
                });

            modelBuilder.Entity("ArarasHealthHub.Domain.Entities.Order", b =>
                {
                    b.HasOne("ArarasHealthHub.Domain.Identity.ApplicationUser", "ApprovedByAccount")
                        .WithMany()
                        .HasForeignKey("ApprovedByAccountId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ArarasHealthHub.Domain.Entities.Employee", "ApprovedByEmployee")
                        .WithMany()
                        .HasForeignKey("ApprovedByEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ArarasHealthHub.Domain.Identity.ApplicationUser", "CanceledByAccount")
                        .WithMany()
                        .HasForeignKey("CanceledByAccountId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ArarasHealthHub.Domain.Entities.Employee", "CanceledByEmployee")
                        .WithMany()
                        .HasForeignKey("CanceledByEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ArarasHealthHub.Domain.Identity.ApplicationUser", "CreatedByAccount")
                        .WithMany()
                        .HasForeignKey("CreatedByAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ArarasHealthHub.Domain.Entities.Employee", "CreatedByEmployee")
                        .WithMany()
                        .HasForeignKey("CreatedByEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ArarasHealthHub.Domain.Identity.ApplicationUser", "FinalizedByAccount")
                        .WithMany()
                        .HasForeignKey("FinalizedByAccountId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ArarasHealthHub.Domain.Entities.Employee", "FinalizedByEmployee")
                        .WithMany()
                        .HasForeignKey("FinalizedByEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ArarasHealthHub.Domain.Entities.Facility", "OrderFacility")
                        .WithMany()
                        .HasForeignKey("OrderFacilityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ArarasHealthHub.Domain.Entities.OrderStatus", "OrderStatus")
                        .WithMany()
                        .HasForeignKey("OrderStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ArarasHealthHub.Domain.Identity.ApplicationUser", "SeparatedByAccount")
                        .WithMany()
                        .HasForeignKey("SeparatedByAccountId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ArarasHealthHub.Domain.Entities.Employee", "SeparatedByEmployee")
                        .WithMany()
                        .HasForeignKey("SeparatedByEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ApprovedByAccount");

                    b.Navigation("ApprovedByEmployee");

                    b.Navigation("CanceledByAccount");

                    b.Navigation("CanceledByEmployee");

                    b.Navigation("CreatedByAccount");

                    b.Navigation("CreatedByEmployee");

                    b.Navigation("FinalizedByAccount");

                    b.Navigation("FinalizedByEmployee");

                    b.Navigation("OrderFacility");

                    b.Navigation("OrderStatus");

                    b.Navigation("SeparatedByAccount");

                    b.Navigation("SeparatedByEmployee");
                });

            modelBuilder.Entity("ArarasHealthHub.Domain.Entities.OrderItem", b =>
                {
                    b.HasOne("ArarasHealthHub.Domain.Entities.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ArarasHealthHub.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ArarasHealthHub.Domain.Entities.OrderItemLot", b =>
                {
                    b.HasOne("ArarasHealthHub.Domain.Entities.OrderItem", "OrderItem")
                        .WithMany("OrderItemLots")
                        .HasForeignKey("OrderItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ArarasHealthHub.Domain.Entities.StockLot", "StockLot")
                        .WithMany()
                        .HasForeignKey("StockLotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OrderItem");

                    b.Navigation("StockLot");
                });

            modelBuilder.Entity("ArarasHealthHub.Domain.Entities.OrderReturn", b =>
                {
                    b.HasOne("ArarasHealthHub.Domain.Entities.Order", "OriginalOrder")
                        .WithMany()
                        .HasForeignKey("OriginalOrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ArarasHealthHub.Domain.Identity.ApplicationUser", "ReturnedByAccount")
                        .WithMany()
                        .HasForeignKey("ReturnedByAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ArarasHealthHub.Domain.Entities.Employee", "ReturnedByEmployee")
                        .WithMany()
                        .HasForeignKey("ReturnedByEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OriginalOrder");

                    b.Navigation("ReturnedByAccount");

                    b.Navigation("ReturnedByEmployee");
                });

            modelBuilder.Entity("ArarasHealthHub.Domain.Entities.OrderReturnItem", b =>
                {
                    b.HasOne("ArarasHealthHub.Domain.Entities.OrderReturn", "OrderReturn")
                        .WithMany("Items")
                        .HasForeignKey("OrderReturnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ArarasHealthHub.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ArarasHealthHub.Domain.Entities.StockLot", "StockLot")
                        .WithMany()
                        .HasForeignKey("StockLotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OrderReturn");

                    b.Navigation("Product");

                    b.Navigation("StockLot");
                });

            modelBuilder.Entity("ArarasHealthHub.Domain.Entities.Product", b =>
                {
                    b.HasOne("ArarasHealthHub.Domain.Entities.MainCategory", "MainCategory")
                        .WithMany("Products")
                        .HasForeignKey("MainCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ArarasHealthHub.Domain.Entities.PackagingType", "PackagingType")
                        .WithMany("Products")
                        .HasForeignKey("PackagingTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ArarasHealthHub.Domain.Entities.SubCategory", "SubCategory")
                        .WithMany("Products")
                        .HasForeignKey("SubCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MainCategory");

                    b.Navigation("PackagingType");

                    b.Navigation("SubCategory");
                });

            modelBuilder.Entity("ArarasHealthHub.Domain.Entities.ReceivedItem", b =>
                {
                    b.HasOne("ArarasHealthHub.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ArarasHealthHub.Domain.Entities.Receiving", "Receiving")
                        .WithMany("Items")
                        .HasForeignKey("ReceivingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Receiving");
                });

            modelBuilder.Entity("ArarasHealthHub.Domain.Entities.Receiving", b =>
                {
                    b.HasOne("ArarasHealthHub.Domain.Identity.ApplicationUser", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ArarasHealthHub.Domain.Entities.Employee", "Responsible")
                        .WithMany()
                        .HasForeignKey("ResponsibleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ArarasHealthHub.Domain.Entities.Supplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Responsible");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("ArarasHealthHub.Domain.Entities.Stock", b =>
                {
                    b.HasOne("ArarasHealthHub.Domain.Entities.Product", "Product")
                        .WithOne("Stock")
                        .HasForeignKey("ArarasHealthHub.Domain.Entities.Stock", "ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ArarasHealthHub.Domain.Entities.StockAdjustment", b =>
                {
                    b.HasOne("ArarasHealthHub.Domain.Identity.ApplicationUser", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ArarasHealthHub.Domain.Entities.Employee", "Responsible")
                        .WithMany()
                        .HasForeignKey("ResponsibleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Responsible");
                });

            modelBuilder.Entity("ArarasHealthHub.Domain.Entities.StockAdjustmentItem", b =>
                {
                    b.HasOne("ArarasHealthHub.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ArarasHealthHub.Domain.Entities.StockAdjustment", "StockAdjustment")
                        .WithMany("Items")
                        .HasForeignKey("StockAdjustmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ArarasHealthHub.Domain.Entities.StockLot", "StockLot")
                        .WithMany()
                        .HasForeignKey("StockLotId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Product");

                    b.Navigation("StockAdjustment");

                    b.Navigation("StockLot");
                });

            modelBuilder.Entity("ArarasHealthHub.Domain.Entities.StockCost", b =>
                {
                    b.HasOne("ArarasHealthHub.Domain.Entities.Stock", "Stock")
                        .WithOne("StockCost")
                        .HasForeignKey("ArarasHealthHub.Domain.Entities.StockCost", "StockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stock");
                });

            modelBuilder.Entity("ArarasHealthHub.Domain.Entities.StockLot", b =>
                {
                    b.HasOne("ArarasHealthHub.Domain.Entities.ReceivedItem", "ReceivedItem")
                        .WithMany()
                        .HasForeignKey("ReceivedItemId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ArarasHealthHub.Domain.Entities.Stock", "Stock")
                        .WithMany("Lots")
                        .HasForeignKey("StockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReceivedItem");

                    b.Navigation("Stock");
                });

            modelBuilder.Entity("ArarasHealthHub.Domain.Entities.StockMovement", b =>
                {
                    b.HasOne("ArarasHealthHub.Domain.Entities.Employee", "Responsible")
                        .WithMany()
                        .HasForeignKey("ResponsibleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ArarasHealthHub.Domain.Entities.StockLot", "StockLot")
                        .WithMany()
                        .HasForeignKey("StockLotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Responsible");

                    b.Navigation("StockLot");
                });

            modelBuilder.Entity("ArarasHealthHub.Domain.Entities.SubCategory", b =>
                {
                    b.HasOne("ArarasHealthHub.Domain.Entities.MainCategory", "MainCategory")
                        .WithMany("SubCategories")
                        .HasForeignKey("MainCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MainCategory");
                });

            modelBuilder.Entity("ArarasHealthHub.Domain.Entities.Supplier", b =>
                {
                    b.OwnsOne("ArarasHealthHub.Domain.ValueObjects.Address", "Address", b1 =>
                        {
                            b1.Property<int>("SupplierId")
                                .HasColumnType("int");

                            b1.Property<string>("Cep")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)")
                                .HasColumnName("Cep")
                                .HasComment("CEP");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("City")
                                .HasComment("Cidade");

                            b1.Property<string>("Complement")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Complement")
                                .HasComment("Complemento");

                            b1.Property<string>("Neighborhood")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Neighborhood")
                                .HasComment("Bairro");

                            b1.Property<string>("Number")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("Number")
                                .HasComment("Número");

                            b1.Property<string>("State")
                                .IsRequired()
                                .HasMaxLength(2)
                                .HasColumnType("nvarchar(2)")
                                .HasColumnName("State")
                                .HasComment("UF");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("Street")
                                .HasComment("Logradouro");

                            b1.HasKey("SupplierId");

                            b1.ToTable("Suppliers", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("SupplierId");
                        });

                    b.OwnsOne("ArarasHealthHub.Domain.ValueObjects.Contact", "Contact", b1 =>
                        {
                            b1.Property<int>("SupplierId")
                                .HasColumnType("int");

                            b1.Property<string>("Email")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Email")
                                .HasComment("E-mail");

                            b1.Property<string>("Phone")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("Phone")
                                .HasComment("Telefone");

                            b1.HasKey("SupplierId");

                            b1.ToTable("Suppliers", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("SupplierId");
                        });

                    b.Navigation("Address")
                        .IsRequired();

                    b.Navigation("Contact")
                        .IsRequired();
                });

            modelBuilder.Entity("ArarasHealthHub.Domain.Identity.ApplicationUser", b =>
                {
                    b.HasOne("ArarasHealthHub.Domain.Entities.Facility", "Facility")
                        .WithMany("Accounts")
                        .HasForeignKey("FacilityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Facility");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("ArarasHealthHub.Domain.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("ArarasHealthHub.Domain.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("ArarasHealthHub.Domain.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ArarasHealthHub.Domain.Entities.Facility", b =>
                {
                    b.Navigation("Accounts");
                });

            modelBuilder.Entity("ArarasHealthHub.Domain.Entities.MainCategory", b =>
                {
                    b.Navigation("Products");

                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("ArarasHealthHub.Domain.Entities.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("ArarasHealthHub.Domain.Entities.OrderItem", b =>
                {
                    b.Navigation("OrderItemLots");
                });

            modelBuilder.Entity("ArarasHealthHub.Domain.Entities.OrderReturn", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("ArarasHealthHub.Domain.Entities.PackagingType", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("ArarasHealthHub.Domain.Entities.Product", b =>
                {
                    b.Navigation("Stock");
                });

            modelBuilder.Entity("ArarasHealthHub.Domain.Entities.Receiving", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("ArarasHealthHub.Domain.Entities.Stock", b =>
                {
                    b.Navigation("Lots");

                    b.Navigation("StockCost");
                });

            modelBuilder.Entity("ArarasHealthHub.Domain.Entities.StockAdjustment", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("ArarasHealthHub.Domain.Entities.SubCategory", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
